<?php
$num = 8;
echo '1 x ', $num, ' = ', $num * 1;
echo '<br>';
echo '2 x ', $num, ' = ', $num * 2;
echo '<br>';
echo '3 x ', $num, ' = ', $num * 3;
echo '<br>';
echo '4 x ', $num, ' = ', $num * 4;
echo '<br>';
echo '5 x ', $num, ' = ', $num * 5;
echo '<br>';
echo '6 x ', $num, ' = ', $num * 6;
echo '<br>';
echo '7 x ', $num, ' = ', $num * 7;
echo '<br>';
echo '8 x ', $num, ' = ', $num * 8;
echo '<br>';
echo '9 x ', $num, ' = ', $num * 9;
echo '<br>';
echo '10 x ', $num, ' = ', $num * 10;
